# Generated by Django 4.0.6 on 2022-07-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caregory_type',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_caregory',
            new_name='post_category',
        ),
    ]
